### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by etomarat** [SoftwareBrothers/adminjs#1127]
Hi!
Is it possible to turn on "hot reload" for frontend? Where should I start research to do this?
Thanks for considering my request!

**Comment by dziraf** [comment]
You should be able to imitate hot reloading by calling `adminJs.watch()` after creating an instance of AdminJS, where `adminJs` is the created instance. This is slower than e. g. webpack's hot reload because it builds all components into one `components.bundle.js` file so the more custom components you have, the slower it'll be.
