### ISSUE TITLE
Show properties not ids when joint relations

### ISSUE THREAD

**Issue by Tevvek** [SoftwareBrothers/adminjs#1132]
**Describe the problem feature solves**
Sometimes it is preferred to see the name or another property (that is not id) of a joint entity to avoid this, and get more human friendly properties to guide ourselves by:
![image](https://user-images.githubusercontent.com/9537497/167856988-b3d9e271-1e1d-4c60-9512-dbccd79c7cd0.png)

**Describe the solution you'd like**
I'm using `typeorm` and `nestjs` and I am not sure that a solution to this already exists, to reference another field of an entity rather than the id in many-to-one relations.

**Comment by dziraf** [comment]
This is defaulted to: `title`, `name`, `email`, `subject` if such fields are present in your entity, otherwise primary key is used:
https://github.com/SoftwareBrothers/adminjs/blob/a0d2a17d55af39e03cf3b3f5ab8cd5c09bcaaeb6/src/backend/adapters/property/base-property.ts#L22

You can define your title property by adding `isTitle: true` in the property which you want to use as title (in your referenced resource options):
https://docs.adminjs.co/PropertyOptions.html#isTitle

**Comment by Tevvek** [comment]
Oh, I see! I was looking at the docs all wrong. Thanks!
Also, is there a way tell a dropdown that in case a title is not available use id? Right now it just renders nothing although it is a valid option:
![image](https://user-images.githubusercontent.com/9537497/167863808-7e96acae-1f5e-4eab-b1a8-afb8cda8b22d.png)

**Comment by dziraf** [comment]
I don't think you can do that at the moment
