### ISSUE TITLE
Overview for soft-deleted records in table

### ISSUE THREAD

**Issue by brniwllnr-rp** [SoftwareBrothers/adminjs#1140]
**Describe the problem feature solves**
I'm always frustrated when I'm using `paranoid: true` in some `sequelize tables`. 
For everyone who doesn't know, this is for softDeletion, which means, a row in a table won't be deleted permanently, but it'll get an `deletedAt` column filled. In this case, AdminJS isn't displaying this row anymore - and I think that's fine.

**Describe the solution you'd like**
I'm wondering if you could add a small checkbox on the top of every list, like "show deleted records", which will update the list-view (overview table). Respectively, the query has to be extended with `{ paranoid: true }`

**Describe alternatives you've considered**
I know I could build an custom component, copy the layout of the list view and adapt the showing resultset. 
But I think this feature could be useful for everyone who works with paranoid tables.

**Acceptance criteria**

- [ ] "Show deleted records" checkbox on `list view` on tables where `paranoid` is activated
   - you should be able to notice the "paranoid" flag if true or false in the sequelizeOptions / given model instance  
- [ ] Re-render non-soft-deleted records when unchecking this checkbox again.
- [ ] An "Restore record" action when in list-view oder show-view

**Comment by dziraf** [comment]
This isn't so simple because different ORMs/ODMs work differently with soft removal. In Sequelize's case soft deletion happens automatically if `paranoid` is set, in case of TypeORM you must use a different method to soft delete. Adding a checkbox would also require us to extend the List action with a new control element which sometimes should show and sometimes shouldn't. TypeORM allows you to do both hard and soft deletes so we won't be able to determine whether the button should be shown or not.

This could be handled via a separate package e. g. `@adminjs/soft-delete` but if that would require us to create different handlers and UIs based on used adapters, it would be difficult to maintain.

When I had to work with soft removal, I usually duplicated the resource in the sidebar, e. g. `Active Discussions` and `Archived Discussions` where `Archived Discussions` would have a `before` hook that sets a filter to show deleted records.
