### ISSUE TITLE
DynamoDB Adapter

### ISSUE THREAD

**Issue by matiasirpac** [SoftwareBrothers/adminjs#1227]
**Describe the problem feature solves**
DynamoDB is growing a lot and there is already an orm like Dynamoose based on Mongoose, it would be a very good option to be able to use AdminJS with connection to this database as well.

**Describe the solution you'd like**
Create an Adapter for DynamoDB

**Describe alternatives you've considered**
The possibility of creating a Custom Adapter or improving the documentation of how to do it.

**Acceptance criteria**
Generate admin interface with connection to Dynamo

**Comment by dziraf** [comment]
cc @krzysztofstudniarek

**Comment by IFaniry** [comment]
You have an [official adapter for TypeORM](https://github.com/SoftwareBrothers/adminjs-typeorm).

How feasible it is to build an adapter for [typedorm, a TypeORM-inspired ORM?](https://github.com/typedorm/typedorm)

Could you provide some high level guidelines or even some milestone tasks for _building a custom AdminJS adapter_?

**Comment by krzysztofstudniarek** [comment]
@IFaniry there is a very high level guideline in the documentation https://docs.adminjs.co/tutorial-passing-resources.html

You can also follow our contributions guidelines 😉. 

@matiasirpac I'm wondering what is the point of AdminJS for DynamoDB since there is a build in AWS admin panel for DynamDB entries editing?

The only answer I could find is a situation when user have to or more different databases and want to administer them from a single dashboard.

**Comment by IFaniry** [comment]
@krzysztofstudniarek Thank you for your quick response.

After going through the link you gave me, I feel that the dev requirements of what I am trying to do are clearer now.

However, I need further guidance on the contributing guideline part, particularly on the part where I somehow need to run the following hypothetical command and make an npm workspace:

> git submodule add -b master git@github.com:IFaniry/adminjs-dynamodb.git packages/adminjs-dynamodb

I noted [AdminJS Community Slack](https://join.slack.com/t/adminbro/shared_invite/zt-czfb79t1-0U7pn_KCqd5Ts~lbJK0_RA) is a good place to chat about potential further developments.

To speak for @matiasirpac regarding your question, the AWS Admin panel for DynamoDB would do the job for a Developer Personal Project but for business co-workers who are not tech savvy, it would be inconvenient.

And so, a DynamoDB adapter for AdminJS opens business opportunities for Developers who can offer:

- Online transaction processing (OLTP),
- or even OnLine Analytical Processing (OLAP)

for Organizations at a cheap price because Serverless databases like DynamoDB are known to be highly cost-effective.

**Comment by krzysztofstudniarek** [comment]
Thanks for the comment. This make a perfect sen e for me.

As for contributions, does [this](https://github.com/SoftwareBrothers/adminjs/blob/master/CONTRIBUTING.md) makes it a bit more clear?

**Comment by IFaniry** [comment]
Sorry for my late response.

Actually, I am asking you for further guidances on how to set up a new AdminJS package because I am new to `yarn link` and `yarn workspaces`.

Could you quote a part of [your link](https://github.com/SoftwareBrothers/adminjs/blob/master/CONTRIBUTING.md) that says how to set up a new package like _@adminjs/dynamodb_, please?

**Comment by dziraf** [comment]
@IFaniry You won't be able to name it `@adminjs/dynamodb` because `@adminjs/` is organization prefix, you should however be able to name it `adminjs-dynamodb` or something similar.

The key points of releasing a package is having `name`, `main` and `types` fields specified in your `package.json`.

We use https://github.com/semantic-release/semantic-release to automatically publish new versions.

**Comment by dziraf** [comment]
DynamoDB can be used with `@adminjs/mongoose`

**Comment by serjikus22** [comment]
> DynamoDB can be used with `@adminjs/mongoose`

its not closed, because there are errors while resource and database checks for adapters
