### ISSUE TITLE
Login Attempts

### ISSUE THREAD

**Issue by Shpackk** [SoftwareBrothers/adminjs#1243]
Is there a way to add login attempts to the login page? Or Recaptcha? Or any other way to secure login page from Brute Force ?

**Comment by dziraf** [comment]
@sviat9440 contributed a retry mechanism to `@adminjs/express`:
https://github.com/SoftwareBrothers/adminjs-expressjs/blob/5ce6a89d69bca7f8b41a234ef8ffaf980f8992fa/src/authentication/login.handler.ts#L80

If you're using it you should be able to specify `maxRetries` when defining your router:
```
const router = buildAuthenticatedRouter(admin, { maxRetries: 5 })
```

Otherwise, it is still possible with customization. You can for example predefine your router, set up captcha middleware and pass your router to `buildAuthenticatedRouter`.

**Comment by Shpackk** [comment]
@dziraf Thanks for the reply ! I'll try it
