### ISSUE TITLE
API Documentation??

### ISSUE THREAD

**Issue by mwillbanks** [SoftwareBrothers/adminjs#1253]
**Describe the problem feature solves**
A clear document generated from the JSDoc's that used to live... now, there is no way to go and view all of the resource options / etc from the site making things extremely difficult to locate what options are able to be passed.  For example; I am looking for customizing a Resource, however, I cannot determine what all of the various properties are besides digging through a ton of source code and then looking back through to see for instance what the navigation specs are.

**Describe the solution you'd like**
Publish the API documentation along with the current tutorial style navigation.

**Describe alternatives you've considered**
Provide types for everything so I _might_ be able to view everything in VSCode? 

**Acceptance criteria**
* API style documentation published _somewhere_.

**Comment by dziraf** [comment]
The old "API reference" documentation is still available here: https://adminjs-docs.web.app

The new tutorial-styled documentation is what people preferred over API reference when we asked our Slack community; most people couldn't find relevant information there and still asked questions that had been asked numerous amount of times, that's why we switched the priorities.

The API documentation, although still available, hasn't been maintained for a while. The reason is that it's difficult to do so as we currently have around 30 repositories. We'd previously tried to use git submodules with all our repositories to read through JSDocs in source code to generate it, but sometimes there have been issues where certain pages were missing after being deployed etc that we hadn't noticed until someone reported that. I have a few ideas to better automate it but it isn't prioritised right now.

**Comment by dziraf** [comment]
I will close this for now, the new documentation now has a link to the old API Reference in the sidebar.
