### ISSUE TITLE
How to "minify" design-system.bundle.js so dashboard doesn't take 20 seconds to load.

### ISSUE THREAD

**Issue by Cod4h** [SoftwareBrothers/adminjs#1270]
I'm facing an issue when I connect to my adminjs panel remotely:

When I go to my adminjs panel URL it takes 20 seconds to load the login page and sometimes it takes even more.

![1](https://user-images.githubusercontent.com/87586393/194492349-5a2d4a91-6f4a-449e-8485-7f9f21db7631.png)

For some reason "design-system.bundle.js" from frontend/assets/ is 35,86 MB.

I know that there is already a closed issue related to this but that answer didn't work for me.

I have already tried adding this piece of code inside my start function in app.js:

```
process.env.NODE_ENV = 'production';
    process.env.ADMIN_JS_SKIP_BUNDLE= true;

    const admin = new AdminJS(AdminJSOptions)

    if (process.env.NODE_ENV === 'production') {
        await admin.initialize();
    }
    else {
        admin.watch();
    }
```

but nothing changes, load time is the same.

Also, when I go to (myurl)/frontend/assets/design-system.bundle.js I can see that the file is huge and it is not bundled or minified.

How can I make this work so it takes less time and uses less data or how can I bundle that giant js file?

Thanks!

**Comment by dziraf** [comment]
The bundles are minified only if your `NODE_ENV` is `production`.

Nevertheless, design system bundle is still huge. I've recently done some changes which reduce the production bundle size from 6-7MB to 2-3MB but that's still big. The size comes from `@carbon/icons-react` library, otherwise design system would probably be around 500KB. I plan to either remove `Icon` component from the design system or rewrite it so that it's only a wrapper around any other icon library you choose but this will be a breaking change so we're waiting for more changes to push alongside it.

**Comment by Cod4h** [comment]
Hello dziraf! Thanks for answering.

I already saw in another similar issue that you answered that I should set NODE_ENV to "production" so the bundle gets minified.

The problem is that I already set `process.env.NODE_ENV = 'production';` before creating the adminjs object but it stills doesn't get minified.

Am I doing it wrong by adding that line in the app.js code before creating adminjs?
If yes, where should I set that enviroment variable instead? (I'm testing in a Windows enviroment).
