### ISSUE TITLE
named export ComponentLoader not found

### ISSUE THREAD

**Issue by jmaric** [SoftwareBrothers/adminjs#1303]
* adminjs@6.6.5
* @adminjs/express@5.0.1
* @adminjs/sequelize@3.0.0

I have been trying to customize my Adminjs component from Node js and when I import ComponentLoader  there is error
named export ComponentLoader not found

Later on I tried to import pkg from 'adminjs'
and then  'const {ComponentLoader} = pkg'
But then it says:

 Trying to bundle file 'file:/Users/Josip/WebstormProjects/ferry-backend/components/dashboard.jsx' but it doesn't exist

![image](https://user-images.githubusercontent.com/25462757/202858596-cd966811-0d8b-47e4-afef-c3a815612400.png)

`
import {ComponentLoader} from "adminjs";

const componentLoader = new ComponentLoader()
const Components = {
    MyDashboard: componentLoader.override('Dashboard','../components/dashboard')
}

AdminJS.registerAdapter(AdminJSSequelize)
const admin = new AdminJS({
    databases: [],
    rootPath: '/admin',
    resources:[UsersResources, GuestResources, SalesResources, FinancesResources],
    components:{
        edit: Components.MyDashboard
    },
    componentLoader

})
`

**Comment by dziraf** [comment]
To override the Dashboard I suggest just using `.add` instead of `.override` and assigning it in `AdminJSOptions`:

```
dashboard: {
  component: Components.MyDashboard,
}
```

**Comment by jamesSaporito** [comment]
@jmaric or anyone else experiencing this issue.

Unsure if it's exactly the same issue, but I ran into this error earlier today. 

It _should_ work if you provide the absolute file path rather than just the current directory like `./filename.js`. The reason this was failing for me is because when it obtains the file path it appends `file:` to the beginning of the string. For example, it would be `file:/Users/path/to/file.js`

`fs.existsSync()` is then used to check if the file exists, which doesn't seem to work when the string starts with `file:`. So by doing the following you shouldn't have any problems as it won't try and resolve the absolute file path, therefore `file:` will not appended:

```js
MyInput: componentLoader.add('MyInput', '/absolute/path/to/file.jsx'),
```

To avoid hard coding it, you could do something like this:

```js
import path from 'path';
import { fileURLToPath } from 'url';

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

const Components = {
    MyInput: componentLoader.add('MyInput', `${dirname}/file.jsx`),
};

export { componentLoader, Components };
```

That being said, it still might be a better idea to go with what @dziraf suggested for your particular use case.

@dziraf Any further thoughts about this? This error occurred both running on my Macbook Pro as well as a Docker environment, which uses the official Node image.
