### ISSUE TITLE
Many-To-Many relations are not shown

### ISSUE THREAD

**Issue by skilletti** [SoftwareBrothers/adminjs#1391]
### What happened?

I set up the AdminJS panel in NestJS with TypeORM.

AdminJs is a really awesome tool. For some reason, the many-to-many relations are not shown. GET requests return everything without issues. Many-To-One relations are also working fine. Here are my entities:

```
@Entity('message')
export class Message extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  readonly id: string;

  @ManyToMany(() => MessageLocalized, (title) => title.id, { eager: true, cascade: true, onDelete: 'CASCADE' })
  @JoinTable({ name: 'message_localized' })
  messageLocalized: MessageLocalized[];
}
```

```
@Entity('message_language')
export class MessageLocalized extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  readonly id: string;

  @Column({ nullable: true })
  title: string;

  @Column({ length: 500 })
  text: string;

  @Column({ type: 'enum', enum: LanguageEnum })
  language: LanguageEnum;
}
```

### Bug prevalence

When I open a Resource

### AdminJS dependencies version

```
    "@adminjs/express": "^5.1.0",
    "@adminjs/nestjs": "^5.1.0",
    "@adminjs/typeorm": "^4.0.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/typeorm": "^9.0.1",
    "@types/bcrypt": "^5.0.0",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "dotenv-flow": "^3.2.0",
    "mysql2": "^2.3.3",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.10"
```

### What browsers do you see the problem on?

Firefox, Chrome

**Comment by dziraf** [comment]
`m:n` and `1:m` relations are currently not supported in core AdminJS, this is something you'd have to implement yourself if you need this. We'd like to add support for these relations either in v7 or v8 of AdminJS but there are several problems we're facing:

1. The solution has to be generic, meaning it should work with any database.
2. There are UI considerations we have to think of such as displaying multiple `1:m` and `m:n` relations in a single view which should support both pagination and filters (currently filters and pagination read from browser's URL which wouldn't work with multiple lists).
3. Data management considerations - while it's much simpler in case of `1:m`, the junction table of `m:n` relation can have extra columns, example:
Table `users` is in `m:n` relationship with table `users` through `users_subscribers` junction table. The junction table has an additional `comment` column which allows the user to save a comment about another user when they subscribe to them. With current implementation of AdminJS, adding `comment` won't be possible.
4. Core logic and adapters would have to be updated so that they can fetch extra records through a junction table.

If your case is much simpler, you can have a look at an example created by @franka107:
https://github.com/franka107/nestjs-adminjs-manytomany-example

**Comment by skilletti** [comment]
Okay, thank you for the info
