### ISSUE TITLE
[Bug]: Relations doesn't seem to work when you specify listPropertyies, editProperties, showProperties, etc...

### ISSUE THREAD

**Issue by JayNisbett** [SoftwareBrothers/adminjs#1572]
### What happened?

I am unable to make the relations feature work unless I show all of the fields for the resource (using postgres adapter).

### Bug prevalence

Every time, so far

### AdminJS dependencies version

"@adminjs/express": "^6.0.1",
    "@adminjs/relations": "^1.0.0",
    "@adminjs/sql": "^2.2.1",
    "adminjs": "^7.3.0",

**Comment by dziraf** [comment]
Can you share your code? I've just tried to add `listProperties` and `showProperties` to the example from the docs and it worked fine for me.

<img width="1104" alt="Screenshot 2023-10-19 at 17 17 58" src="https://github.com/SoftwareBrothers/adminjs/assets/16668924/9281094a-8c27-4ec4-8bf1-8f299d9eba69">

Make sure that if you modify `showProperties` of `Organization` (in this case), it should include `relations` property as it's what `@adminjs/relations`  uses to show the tables:
```
    showProperties: ['name', 'relations'],
```

Since features are basically extensions to resource options, they're merged with your own resource options and your own options take precedence. When you set `showProperties` to just `['name']` it basically disables other fields.

**Comment by JayNisbett** [comment]
Ahh - it was the "relations" property... Thanks!
