### ISSUE TITLE
How to access backend data from frontend component AdminBro?

### ISSUE THREAD

**Issue by bennaaym** [SoftwareBrothers/adminjs#1583]
Hello I have a function that calculate sum of money spent by user. I want to use this function in my frontend component to plot the data on the dashboard of admin bro how can I achieve that? Thank you.

**Comment by dziraf** [comment]
@bennaaym We don't provide support for AdminBro anymore since we'd rebranded to AdminJS 2 years ago.

You can use `ApiClient` to run requests against AdminJS backend, an example for dashboard is in the docs:
https://docs.adminjs.co/ui-customization/dashboard-customization#optional-creating-a-handler-for-your-dashboard-to-access-server-data
