### ISSUE TITLE
Does AdminJS build react app on demand or server start?

### ISSUE THREAD

**Issue by shahidcodes** [SoftwareBrothers/adminjs#924]
I've just deployed my first adminjs app on ec2 free tier. Locally everything works very smoothly and fast. But on ec2 it works very very slow. The login page takes about 10s to load every time.

How do I speed it up? I guess this is something to do with compiling the react components?

**Comment by dziraf** [comment]
Yes, by default AdminJS begins the bundling process on server start which can take up to 1 minute depending on how many custom components you have.

You can optimise it by bundling the components manually during your CI/CD phase or before you run the deploy by yourself. This is how you can create the `.js` packages: https://github.com/SoftwareBrothers/adminjs/blob/master/packages/adminjs-demo/src/utils/bundle.ts

After you build the `.js` files you should put them in a public directory with static files or upload them to i. e. S3 and use https://docs.adminjs.co/AdminJSOptions.html#assetsCDN to point to them

Also note that the minified package is created only if your `NODE_ENV` is `production`, otherwise the design system bundle will be around 50MB.

Lastly, to avoid re-bundling on server start, add this somewhere after you instantiate AdminJS:

```
const adminJs = new AdminJS(...);
...
if (process.env.NODE_ENV === 'production') await adminJs.initialize();
else adminJs.watch();
```
