### ISSUE TITLE
More documentation about custom actions

### ISSUE THREAD

**Issue by fabiosantoscode** [SoftwareBrothers/adminjs#995]
**Describe the problem feature solves**
I'm currently trying to implement a custom bulk action and I found some places that weren't documented enough 

**Describe the solution you'd like**
- the ./path-to-component example as an argument to AdminJS.bundle() should mention where "." is. In retrospect it's probably CWD and not resolved like a require() but I ended up using __dirname after a few attempts.
- The documentation should provide at least one example of implementing a component for a custom action (using its props), and maybe components for other things.

**Describe alternatives you've considered**
I ended up using a lot of console.log, reading the source and guessing things.

**Acceptance criteria**
Described "solution you'd like"

---

I'm open to pushing a PR to the documentation so let me know if you'd like me to.

**Comment by dziraf** [comment]
We've updated our documentation last year and moved to GitBook. I'm closing this since at least the first point is no longer valid (we're now enforcing the usage of ComponentLoader). If you still think that the documentation could be improved, please open a new issue.

Contributions to our documentation are also welcome: https://github.com/SoftwareBrothers/adminjs-docs
